name: Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5 # Upgraded to v5 while we are at it
      with:
        python-version: '3.10'
        
    - name: Install requirements
      run: pip install ".[dev]"
      
    - name: Run tests and collect coverage
      run: pytest --cov=src/taoistmc --cov-report=xml
      
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Passed as an input parameter here